#!/usr/bin/python3

def trigger_custom_error():
    """Cause a TypeError exception to be raised."""
    raise TypeError("Custom error message: Incorrect data type encountered.")
